export const peers = [
  {
    peerId: "QmT445nNLXbqTpnoZmUTdU5iizTWbbVLTTrYpbKA6AZoia",
    client: { type: "Lotus", version: "0.2.0" },
    location: { Lat: 51.51494, Lon: 7.466 },
    city: "Detmond",
    country: "Germany",
    ISP: "Hetzner",
  },
  {
    peerId: "hH6343Xp9yUiGJKJWGYYlaHBA5ZRA9T7CTKLbgh4fdas",
    client: { type: "Lotus", version: "0.2.8" },
    location: { Lat: 42.7, Lon: 23.333 },
    city: "Sofia",
    country: "Bulgaria",
    ISP: "Hetzner",
  },
  {
    peerId: "4hFaMKHjt2xBNAxWXazIWx87z3YDsTmKaiifIa43at9",
    client: { type: "Lotus", version: "0.2.1" },
    location: { Lat: 51.933, Lon: 4.467 },
    city: "Rotterdam",
    country: "Netherlands",
    ISP: "Hetzner",
  },
  {
    peerId: "Wj2LgQXymTopKUff1fmM2QJ6MtAfk1x94NNLqSeD",
    client: { type: "Lotus", version: "0.2.4" },
    location: { Lat: 49.25, Lon: -123.1 },
    city: "Vancouver",
    country: "Canada",
    ISP: "Hetzner",
  },
  {
    peerId: "uPLfb8IJAcUfgBX6TIDxiOWIRxOKLwgYZyJQ0eMr",
    client: { type: "Lotus", version: "0.2.8" },
    location: { Lat: 42.333, Lon: -83.05 },
    city: "Detroit",
    country: "Michigan",
    ISP: "Hetzner",
  },
  {
    peerId: "1CMHE0IA8meMzarsggXMM4czdlQOYxlzDC4CVU96",
    client: { type: "Lotus", version: "0.3.0" },
    location: { Lat: 37.967, Lon: 23.717 },
    city: "Athens",
    country: "Greece",
    ISP: "Hetzner",
  },
  {
    peerId: "QmT445nNLXbqTpnoZmUTdU5iizTWbbVLTTrYpbKA6AZoia",
    client: { type: "Lotus", version: "0.8.0" },
    location: { Lat: 45.517, Lon: -122.667 },
    city: "Portland",
    country: "United States",
    ISP: "Hetzner",
  },
  {
    peerId: "cBWnIB2JSUkQcEQPN40mj7uOhvPtm2kNILP8Jbv3",
    client: { type: "Lotus", version: "1.0.0" },
    location: {
      Lat: 23.5587,
      Lon: -46.625,
    },
    city: "Sao Paolo",
    country: "Brazil",
    ISP: "Hetzner",
  },
];
